version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: vault_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: vault_backend
    # Указываем Docker, где искать Dockerfile
    build:
      context: ./backend # <--- ИЗМЕНЕНО
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    depends_on:
      - db
    restart: unless-stopped

  bot:
    container_name: vault_bot
    # Указываем Docker, где искать Dockerfile
    build:
      context: ./bot # <--- ИЗМЕНЕНО
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_BASE_URL: "http://backend:8000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: